pipeline {
    agent any

    environment {
        BUILD_DIR = "build"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', credentialsId: 'github_credentials', url: 'https://github.com/your-repo.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                script {
                    bat '''
                    choco install doxygen.install graphviz -y
                    '''
                }
            }
        }

        stage('Configure CMake') {
            steps {
                script {
                    bat '''
                    cmake -B %BUILD_DIR% -DCMAKE_BUILD_TYPE=Release -S .
                    '''
                }
            }
        }

        stage('Build') {
            steps {
                script {
                    bat '''
                    cmake --build %BUILD_DIR% --config Release
                    '''
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    bat '''
                    cd %BUILD_DIR%
                    ctest --build-config Release
                    '''
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: "build/**", allowEmptyArchive: true
        }
        failure {
            echo "Build failed!"
        }
        success {
            echo "Build successful!"
        }
    }
}
